import type { CurrencyItem } from '../types';
const codes = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHF",
  "CLF",
  "CLP",
  "CNH",
  "CNY",
  "COP",
  "CRC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HRK",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLE",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "UYU",
  "UZS",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XDR",
  "XOF",
  "XPF",
  "YER",
  "ZAR",
  "ZMW",
  "ZWL",
  "BOV",
  "CHE",
  "CHW",
  "COU",
  "CUC",
  "MRO",
  "SLL",
  "ZRN",
  "GQE"
] as const;
const names: Record<string, string> = {
  "AED": "UAE Dirham",
  "AFN": "Afghan Afghani",
  "ALL": "Albanian Lek",
  "AMD": "Armenian Dram",
  "ANG": "Netherlands Antillean Guilder",
  "AOA": "Angolan Kwanza",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AWG": "Aruban Florin",
  "AZN": "Azerbaijani Manat",
  "BAM": "Bosnia-Herzegovina Mark",
  "BBD": "Barbadian Dollar",
  "BDT": "Bangladeshi Taka",
  "BGN": "Bulgarian Lev",
  "BHD": "Bahraini Dinar",
  "BIF": "Burundian Franc",
  "BMD": "Bermudian Dollar",
  "BND": "Brunei Dollar",
  "BOB": "Bolivian Boliviano",
  "BRL": "Brazilian Real",
  "BSD": "Bahamian Dollar",
  "BTN": "Bhutanese Ngultrum",
  "BWP": "Botswana Pula",
  "BYN": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "CAD": "Canadian Dollar",
  "CDF": "Congolese Franc",
  "CHF": "Swiss Franc",
  "CLF": "Unidad de Fomento",
  "CLP": "Chilean Peso",
  "CNH": "Offshore Yuan",
  "CNY": "Chinese Yuan",
  "COP": "Colombian Peso",
  "CRC": "Costa Rican Colón",
  "CUP": "Cuban Peso",
  "CVE": "Cape Verdean Escudo",
  "CZK": "Czech Koruna",
  "DJF": "Djiboutian Franc",
  "DKK": "Danish Krone",
  "DOP": "Dominican Peso",
  "DZD": "Algerian Dinar",
  "EGP": "Egyptian Pound",
  "ERN": "Eritrean Nakfa",
  "ETB": "Ethiopian Birr",
  "EUR": "Euro",
  "FJD": "Fijian Dollar",
  "FKP": "Falkland Islands Pound",
  "GBP": "British Pound",
  "GEL": "Georgian Lari",
  "GHS": "Ghanaian Cedi",
  "GIP": "Gibraltar Pound",
  "GMD": "Gambian Dalasi",
  "GNF": "Guinean Franc",
  "GTQ": "Guatemalan Quetzal",
  "GYD": "Guyanese Dollar",
  "HKD": "Hong Kong Dollar",
  "HNL": "Honduran Lempira",
  "HRK": "Croatian Kuna",
  "HTG": "Haitian Gourde",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli Shekel",
  "INR": "Indian Rupee",
  "IQD": "Iraqi Dinar",
  "IRR": "Iranian Rial",
  "ISK": "Icelandic Krona",
  "JMD": "Jamaican Dollar",
  "JOD": "Jordanian Dinar",
  "JPY": "Japanese Yen",
  "KES": "Kenyan Shilling",
  "KGS": "Kyrgyzstani Som",
  "KHR": "Cambodian Riel",
  "KMF": "Comorian Franc",
  "KPW": "North Korean Won",
  "KRW": "South Korean Won",
  "KWD": "Kuwaiti Dinar",
  "KYD": "Cayman Islands Dollar",
  "KZT": "Kazakhstani Tenge",
  "LAK": "Lao Kip",
  "LBP": "Lebanese Pound",
  "LKR": "Sri Lankan Rupee",
  "LRD": "Liberian Dollar",
  "LSL": "Lesotho Loti",
  "LYD": "Libyan Dinar",
  "MAD": "Moroccan Dirham",
  "MDL": "Moldovan Leu",
  "MGA": "Malagasy Ariary",
  "MKD": "Macedonian Denar",
  "MMK": "Myanmar Kyat",
  "MNT": "Mongolian Tögrög",
  "MOP": "Macanese Pataca",
  "MRU": "Mauritanian Ouguiya",
  "MUR": "Mauritian Rupee",
  "MVR": "Maldivian Rufiyaa",
  "MWK": "Malawian Kwacha",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "MZN": "Mozambican Metical",
  "NAD": "Namibian Dollar",
  "NGN": "Nigerian Naira",
  "NIO": "Nicaraguan Córdoba",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "OMR": "Omani Rial",
  "PAB": "Panamanian Balboa",
  "PEN": "Peruvian Sol",
  "PGK": "Papua New Guinean Kina",
  "PHP": "Philippine Peso",
  "PKR": "Pakistani Rupee",
  "PLN": "Polish Zloty",
  "PYG": "Paraguayan Guarani",
  "QAR": "Qatari Riyal",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "RUB": "Russian Ruble",
  "RWF": "Rwandan Franc",
  "SAR": "Saudi Riyal",
  "SBD": "Solomon Islands Dollar",
  "SCR": "Seychellois Rupee",
  "SDG": "Sudanese Pound",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "SHP": "Saint Helena Pound",
  "SLE": "Sierra Leonean Leone",
  "SOS": "Somali Shilling",
  "SRD": "Surinamese Dollar",
  "SSP": "South Sudanese Pound",
  "STN": "São Tomé and Príncipe Dobra",
  "SYP": "Syrian Pound",
  "SZL": "Swazi Lilangeni",
  "THB": "Thai Baht",
  "TJS": "Tajikistani Somoni",
  "TMT": "Turkmenistan Manat",
  "TND": "Tunisian Dinar",
  "TOP": "Tongan Paʻanga",
  "TRY": "Turkish Lira",
  "TTD": "Trinidad and Tobago Dollar",
  "TWD": "New Taiwan Dollar",
  "TZS": "Tanzanian Shilling",
  "UAH": "Ukrainian Hryvnia",
  "UGX": "Ugandan Shilling",
  "USD": "US Dollar",
  "UYU": "Uruguayan Peso",
  "UZS": "Uzbekistani Som",
  "VES": "Venezuelan Bolívar",
  "VND": "Vietnamese Dong",
  "VUV": "Vanuatu Vatu",
  "WST": "Samoan Tala",
  "XAF": "Central African CFA Franc",
  "XCD": "East Caribbean Dollar",
  "XDR": "Special Drawing Rights",
  "XOF": "West African CFA Franc",
  "XPF": "CFP Franc",
  "YER": "Yemeni Rial",
  "ZAR": "South African Rand",
  "ZMW": "Zambian Kwacha",
  "ZWL": "Zimbabwean Dollar",
  "BOV": "Bolivian Mvdol",
  "CHE": "WIR Euro",
  "CHW": "WIR Franc",
  "COU": "Unidad de Valor Real",
  "CUC": "Cuban Convertible Peso",
  "MRO": "Mauritanian Ouguiya (old)",
  "SLL": "Sierra Leonean Leone (old)",
  "ZRN": "Zairean New Zaire",
  "GQE": "Equatorial Guinean Ekwele"
};
const seededRates: Record<string, number> = {
  "EUR": 1.0,
  "USD": 0.92,
  "GBP": 1.17,
  "CHF": 1.04,
  "PLN": 0.23,
  "JPY": 0.0061,
  "SEK": 0.088,
  "NOK": 0.086,
  "CAD": 0.68,
  "AUD": 0.61,
  "CZK": 0.041,
  "HUF": 0.0026,
  "NZD": 0.56,
  "MXN": 0.052,
  "CNY": 0.127,
  "INR": 0.011,
  "BRL": 0.18,
  "ARS": 0.0011,
  "TRY": 0.03,
  "RUB": 0.01,
  "AED": 0.25,
  "SAR": 0.245,
  "ZAR": 0.05,
  "SGD": 0.68,
  "HKD": 0.118,
  "TWD": 0.028,
  "KRW": 0.00069,
  "ILS": 0.24,
  "RON": 0.2,
  "BGN": 0.51,
  "DKK": 0.134,
  "ISK": 0.0067,
  "NPR": 0.0075,
  "PKR": 0.0034,
  "THB": 0.026,
  "PHP": 0.016,
  "VND": 3.6e-05,
  "IDR": 5.8e-05,
  "MYR": 0.2,
  "KWD": 3.05,
  "BHD": 2.45,
  "OMR": 2.38,
  "QAR": 0.25,
  "JOD": 1.3,
  "EGP": 0.019,
  "MAD": 0.092,
  "TND": 0.3,
  "DZD": 0.0069,
  "CLP": 0.00097,
  "COP": 0.00023,
  "PEN": 0.24,
  "UYU": 0.023,
  "PYG": 0.00012,
  "BOB": 0.13,
  "CRC": 0.0018,
  "GTQ": 0.12,
  "HNL": 0.037,
  "NIO": 0.025,
  "PAB": 0.92,
  "BZD": 0.46,
  "JMD": 0.0058,
  "TTD": 0.14,
  "BBD": 0.46,
  "BSD": 0.92,
  "CUP": 0.035,
  "DOP": 0.015,
  "GHS": 0.063,
  "NGN": 0.00058,
  "KES": 0.007,
  "UGX": 0.00024
};
function seededRate(code: string): number { const h = code.split('').reduce((a, c) => a + c.charCodeAt(0), 0); return Number((0.03 + ((h % 900) / 1000) + ((h % 13) / 100)).toFixed(4)); }
export const currencyCatalog: CurrencyItem[] = codes.map((code) => ({ code, name: names[code] ?? `Currency ${code}`, flag: '🏳️', rateToEUR: seededRates[code] ?? seededRate(code), region: names[code] ? 'Prepared' : 'Global' }));
export const currencyLookup = Object.fromEntries(currencyCatalog.map((item) => [item.code, item])) as Record<string, CurrencyItem>;
export const curatedFavorites = ['USD', 'GBP', 'CHF', 'PLN', 'EUR'];
export function getCurrency(code: string): CurrencyItem { return currencyLookup[code] ?? currencyCatalog[0]; }
export function getRateToEUR(code: string, liveRates?: Record<string, number> | null): number { if (liveRates && typeof liveRates[code] === 'number') return 1 / liveRates[code]; return getCurrency(code).rateToEUR; }
export function formatMoney(value: number, lang: string, digits = 2): string { return new Intl.NumberFormat(lang === 'zhHans' ? 'zh-CN' : lang, { maximumFractionDigits: digits, minimumFractionDigits: value < 1 ? Math.min(4, digits) : Math.min(2, digits) }).format(value); }
export function formatRate(rate: number, lang: string): string { return new Intl.NumberFormat(lang === 'zhHans' ? 'zh-CN' : lang, { maximumFractionDigits: 4, minimumFractionDigits: 4 }).format(rate); }
export function convertAmount(amount: number, from: string, to: string, liveRates?: Record<string, number> | null): number { const rateFrom = getRateToEUR(from, liveRates); const rateTo = getRateToEUR(to, liveRates); return (amount * rateFrom) / rateTo; }
